### ISSUE TITLE
Update url doesn't work

### ISSUE THREAD

**Issue by MelanX** [Darkhax-Minecraft/Effect-Tooltips#1]
```
[16:29:18] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [effecttooltips] Starting version check at https://updates.blamejared.com/get?n=effecttooltips&gv=1.19.1
[16:29:18] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar%23146!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%23146!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%23146!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%23146!/:?] {}
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[fmlcore-1.19.1-42.0.1.jar%23185!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?] {re:mixin}
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.19.1-42.0.1.jar%23185!/:?] {}
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%23146!/:?] {}
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.9.jar%23146!/:?] {}
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%23146!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%23146!/:?] {}
	... 6 more
```

If you go to https://updates.blamejared.com/get?n=effecttooltips&gv=1.19.1, it says `Invalid projectName "effecttooltips" and gameVersion "1.19.1"!`
Even if I try changing it to 1.19, it still doesn't work.

**Comment by Darkhax** [comment]
Thanks for letting me know, forgot to run the Gradle task that updates that.
